// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package main

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NodeMessage struct {
	Command              string   `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Parameters           [][]byte `protobuf:"bytes,2,rep,name=Parameters,proto3" json:"Parameters,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeMessage) Reset()         { *m = NodeMessage{} }
func (m *NodeMessage) String() string { return proto.CompactTextString(m) }
func (*NodeMessage) ProtoMessage()    {}
func (*NodeMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *NodeMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeMessage.Unmarshal(m, b)
}
func (m *NodeMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeMessage.Marshal(b, m, deterministic)
}
func (m *NodeMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeMessage.Merge(m, src)
}
func (m *NodeMessage) XXX_Size() int {
	return xxx_messageInfo_NodeMessage.Size(m)
}
func (m *NodeMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeMessage.DiscardUnknown(m)
}

var xxx_messageInfo_NodeMessage proto.InternalMessageInfo

func (m *NodeMessage) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

func (m *NodeMessage) GetParameters() [][]byte {
	if m != nil {
		return m.Parameters
	}
	return nil
}

type Addrs struct {
	Address              [][]byte `protobuf:"bytes,1,rep,name=Address,proto3" json:"Address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Addrs) Reset()         { *m = Addrs{} }
func (m *Addrs) String() string { return proto.CompactTextString(m) }
func (*Addrs) ProtoMessage()    {}
func (*Addrs) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *Addrs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Addrs.Unmarshal(m, b)
}
func (m *Addrs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Addrs.Marshal(b, m, deterministic)
}
func (m *Addrs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Addrs.Merge(m, src)
}
func (m *Addrs) XXX_Size() int {
	return xxx_messageInfo_Addrs.Size(m)
}
func (m *Addrs) XXX_DiscardUnknown() {
	xxx_messageInfo_Addrs.DiscardUnknown(m)
}

var xxx_messageInfo_Addrs proto.InternalMessageInfo

func (m *Addrs) GetAddress() [][]byte {
	if m != nil {
		return m.Address
	}
	return nil
}

type NodeInfoMessage struct {
	NodeType             uint32   `protobuf:"varint,1,opt,name=NodeType,proto3" json:"NodeType,omitempty"`
	ID                   string   `protobuf:"bytes,2,opt,name=ID,proto3" json:"ID,omitempty"`
	Addrs                *Addrs   `protobuf:"bytes,3,opt,name=Addrs,proto3" json:"Addrs,omitempty"`
	Extra                string   `protobuf:"bytes,4,opt,name=Extra,proto3" json:"Extra,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeInfoMessage) Reset()         { *m = NodeInfoMessage{} }
func (m *NodeInfoMessage) String() string { return proto.CompactTextString(m) }
func (*NodeInfoMessage) ProtoMessage()    {}
func (*NodeInfoMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}

func (m *NodeInfoMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeInfoMessage.Unmarshal(m, b)
}
func (m *NodeInfoMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeInfoMessage.Marshal(b, m, deterministic)
}
func (m *NodeInfoMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeInfoMessage.Merge(m, src)
}
func (m *NodeInfoMessage) XXX_Size() int {
	return xxx_messageInfo_NodeInfoMessage.Size(m)
}
func (m *NodeInfoMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeInfoMessage.DiscardUnknown(m)
}

var xxx_messageInfo_NodeInfoMessage proto.InternalMessageInfo

func (m *NodeInfoMessage) GetNodeType() uint32 {
	if m != nil {
		return m.NodeType
	}
	return 0
}

func (m *NodeInfoMessage) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *NodeInfoMessage) GetAddrs() *Addrs {
	if m != nil {
		return m.Addrs
	}
	return nil
}

func (m *NodeInfoMessage) GetExtra() string {
	if m != nil {
		return m.Extra
	}
	return ""
}

func init() {
	proto.RegisterType((*NodeMessage)(nil), "main.NodeMessage")
	proto.RegisterType((*Addrs)(nil), "main.Addrs")
	proto.RegisterType((*NodeInfoMessage)(nil), "main.NodeInfoMessage")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 200 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xc9, 0x4d, 0xcc, 0xcc, 0x53,
	0x72, 0xe7, 0xe2, 0xf6, 0xcb, 0x4f, 0x49, 0xf5, 0x85, 0x48, 0x09, 0x49, 0x70, 0xb1, 0x27, 0xe7,
	0xe7, 0xe6, 0x26, 0xe6, 0xa5, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0xc1, 0xb8, 0x42, 0x72,
	0x5c, 0x5c, 0x01, 0x89, 0x45, 0x89, 0xb9, 0xa9, 0x25, 0xa9, 0x45, 0xc5, 0x12, 0x4c, 0x0a, 0xcc,
	0x1a, 0x3c, 0x41, 0x48, 0x22, 0x4a, 0x8a, 0x5c, 0xac, 0x8e, 0x29, 0x29, 0x45, 0xc5, 0x20, 0x23,
	0x40, 0x8c, 0xd4, 0xe2, 0x62, 0x09, 0x46, 0xb0, 0x2a, 0x18, 0x57, 0xa9, 0x8c, 0x8b, 0x1f, 0x64,
	0x97, 0x67, 0x5e, 0x5a, 0x3e, 0xcc, 0x3e, 0x29, 0x2e, 0x0e, 0x90, 0x50, 0x48, 0x65, 0x41, 0x2a,
	0xd8, 0x42, 0xde, 0x20, 0x38, 0x5f, 0x88, 0x8f, 0x8b, 0xc9, 0xd3, 0x45, 0x82, 0x09, 0xec, 0x0c,
	0x26, 0x4f, 0x17, 0x21, 0x98, 0x0d, 0x12, 0xcc, 0x0a, 0x8c, 0x1a, 0xdc, 0x46, 0xdc, 0x7a, 0x20,
	0x0f, 0xe8, 0x81, 0x85, 0x82, 0xa0, 0x76, 0x8b, 0x70, 0xb1, 0xba, 0x56, 0x94, 0x14, 0x25, 0x4a,
	0xb0, 0x80, 0x75, 0x41, 0x38, 0x49, 0x6c, 0x60, 0x0f, 0x1b, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff,
	0x8a, 0xf1, 0x93, 0xb2, 0x01, 0x01, 0x00, 0x00,
}
